### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by 5h44n** [yourlabs/djWebdApp#1]
First, this is an awesome project, thanks for creating it! 🎉 

I've noticed there's an extra migration that gets generated when I run `makemigrations`, titled `0005_alter_account_id_alter_blockchain_id_and_more.py`. Think it just needs to be added to the `djwebdapp` app's migrations same as the previous migration in this [commit](https://github.com/yourlabs/djWebdApp/commit/1c1a2bbfb90449e5877903219cb32170189af5b2). 

Am happy to add this if needed.

**Comment by jpic** [comment]
Hi, thanks for the kind words!

Sorry for the late reply, github is actually just a mirror of yourlabs.io/pyratzlabs/djwebdapp

This issue has been resolved I guess
